#!/usr/bin/env python3
"""Build the docs site from docs/src/*.md.

    uv run --with markdown --with pygments python docs/build.py
    ./docs/build.sh                                  # the same, with the deps pinned

Everything comes from nav.toml: the sidebar, the prev/next pager, llms.txt and
llms-full.txt. One source, so a page cannot be in the site and missing from the
agent index -- which is the failure this would otherwise have, since nobody
looks at llms.txt to notice it is stale.

Output lands in docs/_site/ and is gitignored. CI publishes it; a local build is
for looking at it.
"""
from __future__ import annotations

import html
import re
import shutil
import sys
import tomllib
from pathlib import Path

import markdown

HERE = Path(__file__).resolve().parent
SRC = HERE / "src"
OUT = HERE / "_site"


def load_nav() -> dict:
    with (HERE / "nav.toml").open("rb") as fh:
        return tomllib.load(fh)


EXPLORER = "https://claude.ai/code/artifact/e71cf372-9bd3-4ffd-97c4-298e24ebb7b8"


def load_claims() -> dict:
    """The claims each page makes, keyed by filename.

    Generated by the schema repository's `dev/claims-audit.py --docs-index`,
    because that is where the audit runs and it cannot be read from here. Absent
    is normal -- a docs build in a checkout without it produces pages with no
    footnote rather than failing.
    """
    f = HERE / "claims.json"
    if not f.exists():
        return {}
    import json
    return json.loads(f.read_text())


def claim_footnote(page_file: str, claims: dict) -> str:
    """A quiet line of claim ids at the foot of a page.

    Small on purpose. It is a reference for somebody checking whether a promise
    on this page is tested, not something a reader of the page needs -- so it
    sits under everything, in the smallest legible type, and says the status
    plainly rather than colour-coding it.
    """
    rows = claims.get(page_file) or []
    if not rows:
        return ""
    seen, items = set(), []
    for r in rows:
        if r["id"] in seen:
            continue
        seen.add(r["id"])
        items.append(
            f'<span class="claim-id" title="{html.escape(r["claim"])}">'
            f'{html.escape(r["id"])}<em>{html.escape(r["status"])}</em></span>')
    covered = sum(1 for r in rows if r["status"] == "covered")
    return (
        '<aside class="claims">'
        f'<a href="{EXPLORER}">{covered} of {len(seen)} claims on this page have a test</a> '
        + " ".join(items) + "</aside>")


def load_versions() -> dict:
    """The numbers the pages ask for, flattened to placeholder names.

    ../versions.toml is the one home. Pages write @@extension@@ rather than a
    literal because a literal in prose has no way to announce that it has gone
    stale -- three pages claimed the dialect was 0.1.0 for an entire release
    after it became 0.1.1, and they read exactly as convincingly as the pages
    that were right.
    """
    with (HERE.parent / "versions.toml").open("rb") as fh:
        v = tomllib.load(fh)
    return {
        "extension": v["published"]["extension"],
        "core": v["published"]["core"],
        "chart": v["published"]["chart"],
        "core_min": v["requires"]["core"],
    }


# @@name@@, NOT {{name}}. `{{...}}` is the workflow engine's own template
# syntax -- {{run.$id}}, {{item.code}}, {{items}} -- and these pages document
# it at length, so a substituting build would have eaten the very thing the
# grammar pages exist to show. The strict unknown-placeholder check below is
# what caught that, on the first build, rather than a reader finding a mangled
# example later.
PLACEHOLDER = re.compile(r"@@([a-z_]+)@@")


def substitute(text: str, versions: dict, where: str) -> str:
    """Replace @@name@@ with the number, and refuse an unknown name.

    Refusing matters more than substituting. A typo'd @@verison@@ left as
    literal text on the page is the same class of silent wrongness this file
    exists to remove, so an unknown placeholder stops the build and names the
    page it is on.
    """
    def one(m):
        key = m.group(1)
        if key not in versions:
            raise SystemExit(
                f"{where}: unknown placeholder @@{key}@@ -- "
                f"versions.toml offers {', '.join(sorted(versions))}")
        return versions[key]
    return PLACEHOLDER.sub(one, text)


def pages(nav: dict) -> list[dict]:
    """Flat page list, in nav order -- what the pager and llms.txt walk."""
    out = []
    for section in nav.get("section", []):
        for page in section.get("page", []):
            out.append({**page, "section": section["name"],
                        "url": page["file"].replace(".md", ".html")})
    return out


def render_markdown(text: str) -> tuple[str, str]:
    """Returns (html, first paragraph as plain text).

    `codehilite` with guess_lang off: a fenced block with no language is
    output, not code, and guessing turns a psql table into badly-coloured
    Python. That is exactly the distinction the theme draws.
    """
    md = markdown.Markdown(extensions=[
        "extra", "toc", "sane_lists", "attr_list",
        "codehilite", "admonition",
    ], extension_configs={
        "codehilite": {"css_class": "hl", "guess_lang": False},
    })
    body = md.convert(text)
    first = ""
    m = re.search(r"<p>(.*?)</p>", body, re.S)
    if m:
        first = re.sub(r"<[^>]+>", "", m.group(1)).strip()
    return body, first



def sidebar(nav: dict, current: str) -> str:
    parts = []
    for section in nav.get("section", []):
        parts.append(f'<div class="group">{html.escape(section["name"])}</div>')
        for page in section.get("page", []):
            url = page["file"].replace(".md", ".html")
            cls = ' class="here"' if url == current else ""
            parts.append(f'<a href="{url}"{cls}>{html.escape(page["title"])}</a>')
    return "\n".join(parts)


def pager(all_pages: list[dict], i: int) -> str:
    prev = all_pages[i - 1] if i > 0 else None
    nxt = all_pages[i + 1] if i + 1 < len(all_pages) else None
    left = (f'<a href="{prev["url"]}"><span class="dir">Previous</span>'
            f'{html.escape(prev["title"])}</a>') if prev else "<span></span>"
    right = (f'<a href="{nxt["url"]}" style="text-align:right"><span class="dir">Next</span>'
             f'{html.escape(nxt["title"])}</a>') if nxt else "<span></span>"
    return f'<div class="pager">{left}{right}</div>'


SHELL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — {site}</title>
<meta name="description" content="{summary}">
<link rel="canonical" href="{site_url}/{url}">
<link rel="icon" type="image/png" href="assets/logo.png">
<meta property="og:title" content="{title} — {site}">
<meta property="og:description" content="{summary}">
<meta property="og:type" content="article">
<meta property="og:url" content="{site_url}/{url}">
<!-- Two families and a mono, with real fallbacks: the page is readable before
     anything loads, and stays readable if fonts.gstatic.com is blocked. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;1,6..72,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="theme/style.css">
</head>
<body>
<header class="masthead">
  <div class="masthead-inner">
    <img src="assets/logo.png" alt="">
    <a class="wordmark" href="index.html">{site}</a>
    <span class="tagline">{tagline}</span>
    <span class="spacer"></span>
    <a class="ext" href="https://github.com/percolating-sirsh/get-percolate">GitHub</a>
    <a class="ext" href="llms.txt">llms.txt</a>
  </div>
</header>
<div class="shell">
  <nav class="toc">
{sidebar}
  </nav>
  <main>
{body}
{pager}
  </main>
</div>
<footer class="site"><div class="inner">
  <span>Percolate</span>
  <span class="dot">&bull;</span>
  <a href="https://percolationlabs.ai">Percolation Labs</a>
  <a href="https://github.com/percolating-sirsh/get-percolate">GitHub</a>
  <a href="https://pypi.org/project/percolate-core/">PyPI</a>
  <span class="spacer"></span>
  <span>MIT</span>
</div></footer>
</body>
</html>
"""


def broken_anchors() -> list[str]:
    """Internal links whose `#anchor` matches no heading on the target page.

    The nav check below refuses a page that does not exist. Nothing refused a
    LINK INTO a page that does not exist, or into a heading that does not --
    which renders as a link that quietly lands at the top of the right page, or
    at a 404, and ships because nobody clicks every link.

    Written after producing three of them in one afternoon while editing three
    pages, each caught only because a scan was run by hand. The first one, on
    its own, did not earn this: one instance that never shipped is a risk, not
    an incident. Three in one sitting, with nothing between them and a reader
    except somebody remembering, is the other thing.

    The slug rule mirrors what the renderer does with a heading; if the two ever
    disagree this reports links that are fine, which is the direction that gets
    noticed rather than the one that does not.
    """
    def slug(h: str) -> str:
        s = re.sub(r"""[`*\[\](),.:;?!'"]""", "", h.strip().lower())
        return re.sub(r"[^a-z0-9]+", "-", s).strip("-")

    heads = {f.stem: {slug(m.group(2))
                      for m in re.finditer(r"^(#{2,4})\s+(.*)$", f.read_text(), re.M)}
             for f in SRC.glob("*.md")}
    bad = []
    for f in sorted(SRC.glob("*.md")):
        for m in re.finditer(r"\]\((?:([a-z0-9-]+)\.html)?#([a-z0-9-]+)\)", f.read_text()):
            page, anchor = (m.group(1) or f.stem), m.group(2)
            if page not in heads:
                bad.append(f"{f.name}: links to {page}.html, which is not a page")
            elif anchor not in heads[page]:
                bad.append(f"{f.name}: #{anchor} is not a heading in {page}.md")
    return bad


def build() -> int:
    nav = load_nav()
    versions = load_versions()
    claims = load_claims()
    all_pages = pages(nav)
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    shutil.copytree(HERE / "theme", OUT / "theme")
    shutil.copytree(HERE / "assets", OUT / "assets")

    missing = [p["file"] for p in all_pages if not (SRC / p["file"]).exists()]
    if missing:
        # Loudly, and before writing a site with holes in it. A nav entry with
        # no page renders as a link to a 404, which is the kind of thing that
        # ships because nobody clicks every link.
        print(f"error: nav.toml names pages that do not exist: {', '.join(missing)}",
              file=sys.stderr)
        return 1

    dangling = broken_anchors()
    if dangling:
        print("error: internal links that go nowhere:\n  "
              + "\n  ".join(dangling), file=sys.stderr)
        return 1

    full_md = [f"# {nav['site_name']} — {nav['site_tagline']}\n",
               nav["description"].strip(), ""]
    index_lines = [f"# {nav['site_name']}", "",
                   f"> {nav['description'].strip()}", ""]
    by_section: dict[str, list[str]] = {}

    for i, page in enumerate(all_pages):
        text = substitute((SRC / page["file"]).read_text(), versions, page["file"])
        body, first_para = render_markdown(text)
        summary = page.get("summary") or first_para

        (OUT / page["url"]).write_text(SHELL.format(
            title=html.escape(page["title"]),
            site=html.escape(nav["site_name"]),
            tagline=html.escape(nav["site_tagline"]),
            site_url=nav["site_url"].rstrip("/"),
            url=page["url"],
            summary=html.escape(summary),
            sidebar=sidebar(nav, page["url"]),
            body=body + claim_footnote(page["file"], claims),
            pager=pager(all_pages, i),
        ))

        by_section.setdefault(page["section"], []).append(
            f"- [{page['title']}]({nav['site_url'].rstrip('/')}/{page['url']}): {summary}")
        full_md += [f"\n\n---\n\n## {page['title']}", text]

    # llms.txt -- llmstxt.org: an H1, a blockquote summary, then link sections.
    # Generated from the same nav as the site so it cannot fall behind, which is
    # the whole failure mode of a hand-written one: nobody reads it often enough
    # to notice it is wrong.
    for name, links in by_section.items():
        index_lines += [f"## {name}", "", *links, ""]
    index_lines += [
        "## Source", "",
        "- [Getting started](https://github.com/percolating-sirsh/get-percolate): compose file, Helm chart, install script and the source of these docs.",
        "- [percolate-core on PyPI](https://pypi.org/project/percolate-core/): the worker, Content Server and Agent Runtime.",
        "",
        "## Optional", "",
        f"- [Full documentation as one file]({nav['site_url'].rstrip('/')}/llms-full.txt): every page above, concatenated.",
        "",
    ]
    (OUT / "llms.txt").write_text("\n".join(index_lines))
    (OUT / "llms-full.txt").write_text("\n".join(full_md))

    # No CNAME. The site is served from the project Pages URL, so every link
    # here is one that resolves today; a custom domain can be added later by
    # changing site_url in nav.toml and setting the CNAME in the repo settings.
    #
    # .nojekyll, or Pages runs the whole thing through Jekyll and drops every
    # directory beginning with an underscore.
    (OUT / ".nojekyll").write_text("")

    (OUT / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\nSitemap: {nav['site_url'].rstrip('/')}/sitemap.xml\n")
    urls = "".join(
        f"<url><loc>{nav['site_url'].rstrip('/')}/{p['url']}</loc></url>" for p in all_pages)
    (OUT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>'
        f'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">{urls}</urlset>')

    print(f"built {len(all_pages)} pages + llms.txt + llms-full.txt -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
